import Link from 'next/link'
import { headers } from 'next/headers'

export const dynamic = 'force-dynamic'

import { redirect } from 'next/navigation'
import { auth } from '@/lib/auth'
import { getProjects } from '@/lib/projects'
import { sql } from 'drizzle-orm'
import { db } from '@/lib/db'

async function createProject(formData: FormData){'use server'; const session=await auth.api.getSession({headers:await headers()}); if(!session?.user) redirect('/sign-in'); const tags=String(formData.get('tags')||'').split(',').map(s=>s.trim()).filter(Boolean); await db.execute(sql`INSERT INTO "projects" ("title","description","imageUrl","projectUrl","githubUrl","tags","featured","sortOrder") VALUES (${String(formData.get('title'))},${String(formData.get('description'))},${String(formData.get('imageUrl')||'')},${String(formData.get('projectUrl')||'')},${String(formData.get('githubUrl')||'')},${JSON.stringify(tags)}::jsonb,${formData.get('featured')==='on'},${Number(formData.get('sortOrder')||0)})`); redirect('/admin')}
export default async function Admin(){const session=await auth.api.getSession({headers:await headers()}); if(!session?.user) redirect('/sign-in'); const projects=await getProjects(); return <main className="wrap admin"><header className="nav"><Link href="/" className="mono">← Portfolio</Link><div className="row"><span className="muted">{session.user.email}</span><form action={async()=>{ 'use server'; await auth.api.signOut({headers:await headers()}); redirect('/sign-in')}}><button className="button" type="submit">Sign out</button></form></div></header><div className="admin-grid" style={{marginTop:50}}><section><div className="eyebrow mono">Admin dashboard</div><h1>Manage projects.</h1><p className="muted">Add work here and it will appear on the public portfolio immediately.</p><form action={createProject} style={{marginTop:28}}><label className="label">Title<input className="input" name="title" required /></label><label className="label">Description<textarea className="textarea" name="description" required /></label><label className="label">Tags <span className="mono">(comma separated)</span><input className="input" name="tags" /></label><label className="label">Project URL<input className="input" name="projectUrl" type="url" /></label><label className="label">GitHub URL<input className="input" name="githubUrl" type="url" /></label><label className="label">Image URL<input className="input" name="imageUrl" type="url" /></label><label className="label">Sort order<input className="input" name="sortOrder" type="number" defaultValue="0" /></label><label className="label"><input name="featured" type="checkbox" /> Featured project</label><button className="button primary" type="submit">Publish project</button></form></section><section><div className="eyebrow mono">Published</div><h2>{projects.length} projects</h2><div style={{display:'grid',gap:12,marginTop:20}}>{projects.map(p=><div className="card" style={{minHeight:0,padding:18}} key={p.id}><div className="row" style={{justifyContent:'space-between'}}><strong>{p.title}</strong><span className="mono muted">#{p.sortOrder}</span></div><p>{p.description}</p><div className="tags">{p.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div></div>)}</div></section></div></main>}
